### ISSUE TITLE
書籍編集モードの追加

### ISSUE THREAD

**Issue by kengop** [es-dev-camp/books-management-service#1]
現状、書籍の詳細を開いた時に書籍の内容を編集することができるが、ユースケースとしては低頻度の操作であり、大抵のユーザは書籍の賃貸の操作しか行わないため、デフォルトでは編集できない状態にし、モード切替時にのみ編集できるように回収する。

**Comment by MakotoUwaya** [comment]
回収 → 改修
(回収だけに一応拾う)
