### ISSUE TITLE
ログイン時にユーザー情報を登録・更新する

### ISSUE THREAD

**Issue by MakotoUwaya** [es-dev-camp/books-management-service#22]
#30 の対応で改善される？

**Comment by MakotoUwaya** [comment]
#30 の対応で改善される？

**Comment by kengop** [comment]
firebaseのアカウント情報をベースに利用するため必須ではなくなりました。

**Comment by MakotoUwaya** [comment]
Auth0 対応時までペンディング

**Comment by MakotoUwaya** [comment]
うーん
Auth0 の対応時は #36 で対応してもらった User データモデルを拡張するだけで良くなるから
この Issue はこれで完了にしちゃおう
