### ISSUE TITLE
本の貸し出し状況を可視化する

### ISSUE THREAD

**Issue by kengop** [es-dev-camp/books-management-service#36]
誰がいつどの本を借りたかをユーザが閲覧できるようにする

**Comment by MakotoUwaya** [comment]
https://demos.creative-tim.com/vuetify-material-dashboard/#/dashboard
これ使ってみたい

とりあえず uwayasu bot の購買状況可視化の方で素振りしてみます

**Comment by kengop** [comment]
アプリ公開後の目下の課題としては

「本アプリの利用者がいるのかが傍からみたときに（開発者、ユーザ共に）分からない」

というのがあると考えていまして、これより次の事象に発生していると仮定しました。

「アプリが使われているか分からないため、ユーザが新規にアプリを実際に使用するまでの心理的ハードルが高く、アプリの利用が促進されない」

そこで、まずは簡単にアプリの利用状況をユーザが把握できるようにする、というのが本issueの趣旨となります。

可視化のレベルですが、まずは貸し出し履歴をリスト表示できる画面（もしくはコンポーネント）を作ろうかと。

1. 貸し出しイベントの定義
2. 単純な履歴をリスト表示
3. イベントを集計して期間指定のグラフを作る / Slack通知させる etc...

今回は1,2を実施して、そこから3のほうに着手しようかと。
個人的にはSlack通知を先に着手したい。(ユーザにより身近な環境で利用状況を通知できるので)

**Comment by kengop** [comment]
実装の過程で以下の機能も必要になったので合わせて対応。

ログイン時にGooleのアカウント情報を `/User` に格納する

https://github.com/es-dev-camp/books-management-service/issues/22

**Comment by MakotoUwaya** [comment]
いい感じ！
