### ISSUE TITLE
202001 パッケージ更新

### ISSUE THREAD

**Issue by MakotoUwaya** [es-dev-camp/books-management-service#89]
$ ncu
Checking books-management-service\package.json

 auth0-js                        ^9.11.3  →   ^9.12.1 
 core-js                          ^3.3.6  →    ^3.6.1 
 firebase                         ^7.2.3  →    ^7.6.1 
 vue                             ^2.6.10  →   ^2.6.11 
 vuetify                          ^2.1.9  →   ^2.1.16 
 vuex                             ^3.1.1  →    ^3.1.2 
 vuex-smart-module                ^0.3.1  →    ^0.3.2 
 @babel/core                      ^7.6.4  →    ^7.7.7 
 @babel/preset-env                ^7.6.3  →    ^7.7.7 
 @storybook/addon-a11y            ^5.2.5  →    ^5.2.8 
 @storybook/addon-actions         ^5.2.5  →    ^5.2.8 
 @storybook/addon-backgrounds     ^5.2.5  →    ^5.2.8 
 @storybook/addon-links           ^5.2.5  →    ^5.2.8
 @storybook/addon-storyshots      ^5.2.5  →    ^5.2.8
 @storybook/addon-viewport        ^5.2.5  →    ^5.2.8
 @storybook/theming               ^5.2.5  →    ^5.2.8
 @storybook/vue                   ^5.2.5  →    ^5.2.8
 @types/auth0-js                 ^9.10.6  →   ^9.10.7
 @types/jest                    ^24.0.21  →  ^24.0.25
 @vue/cli-plugin-babel            ^4.0.5  →    ^4.1.2
 @vue/cli-plugin-eslint           ^4.0.5  →    ^4.1.2
 @vue/cli-plugin-pwa              ^4.0.5  →    ^4.1.2
 @vue/cli-plugin-typescript       ^4.0.5  →    ^4.1.2
 @vue/cli-plugin-unit-jest        ^4.0.5  →    ^4.1.2
 @vue/cli-service                 ^4.0.5  →    ^4.1.2
 @vue/eslint-config-prettier      ^5.0.0  →    ^6.0.0
 @vue/eslint-config-typescript    ^4.0.0  →    ^5.0.1
 canvas                           ^2.6.0  →    ^2.6.1
 eslint                          ^5.16.0  →    ^6.8.0
 eslint-plugin-prettier           ^3.1.1  →    ^3.1.2
 eslint-plugin-vue                ^5.2.3  →    ^6.1.2
 firebase-tools                   ^7.6.2  →   ^7.11.0
 husky                            ^3.0.9  →    ^3.1.0
 jest-canvas-mock                 ^2.1.2  →    ^2.2.0
 lint-staged                      ^9.4.2  →    ^9.5.0
 prettier                        ^1.18.2  →   ^1.19.1
 sass                            ^1.23.3  →   ^1.24.0
 ts-jest                         ^24.1.0  →   ^24.2.0
 typescript                       ^3.6.4  →    ^3.7.4
 vue-cli-plugin-vuetify           ^1.1.1  →    ^2.0.3
 vue-loader                      ^15.7.2  →   ^15.8.3
 vue-template-compiler           ^2.6.10  →   ^2.6.11
 vuetify-loader                   ^1.3.0  →    ^1.4.3
 webpack                         ^4.41.2  →   ^4.41.5

Run ncu -u to upgrade package.json

**Comment by WL-Amigo** [comment]
現在の状態で `ncu` を再実行しました

```
 auth0-js                             ^9.11.3  →        ^9.12.2 
 axios                                ^0.19.0  →        ^0.19.2 
 core-js                               ^3.3.6  →         ^3.6.4 
 firebase                              ^7.2.3  →         ^7.7.0 
 vue                                  ^2.6.10  →        ^2.6.11 
 vue-class-component                   ^7.1.0  →         ^7.2.2 
 vue-router                            ^3.1.3  →         ^3.1.5 
 vuex                                  ^3.1.1  →         ^3.1.2 
 vuex-smart-module                     ^0.3.1  →         ^0.3.2 
 @babel/core                           ^7.6.4  →         ^7.8.3 
 @babel/preset-env                     ^7.6.3  →         ^7.8.3 
 @storybook/addon-a11y                 ^5.2.5  →         ^5.3.9 
 @storybook/addon-actions              ^5.2.5  →         ^5.3.9 
 @storybook/addon-backgrounds          ^5.2.5  →         ^5.3.9 
 @storybook/addon-links                ^5.2.5  →         ^5.3.9 
 @storybook/addon-storyshots           ^5.2.5  →         ^5.3.9 
 @storybook/addon-viewport             ^5.2.5  →         ^5.3.9 
 @storybook/theming                    ^5.2.5  →         ^5.3.9 
 @storybook/vue                        ^5.2.5  →         ^5.3.9 
 @types/auth0-js                      ^9.10.6  →        ^9.12.3 
 @types/jest                         ^24.0.21  →        ^24.9.1 
 @vue/cli-plugin-babel                 ^4.0.5  →         ^4.1.2 
 @vue/cli-plugin-eslint                ^4.0.5  →         ^4.1.2 
 @vue/cli-plugin-pwa                   ^4.0.5  →         ^4.1.2 
 @vue/cli-plugin-typescript            ^4.0.5  →         ^4.1.2 
 @vue/cli-plugin-unit-jest             ^4.0.5  →         ^4.1.2 
 @vue/cli-service                      ^4.0.5  →         ^4.1.2 
 @vue/eslint-config-prettier           ^5.0.0  →         ^6.0.0 
 @vue/eslint-config-typescript         ^4.0.0  →         ^5.0.1 
 @vue/test-utils                1.0.0-beta.29  →  1.0.0-beta.31 
 canvas                                ^2.6.0  →         ^2.6.1 
 cross-env                             ^6.0.3  →         ^7.0.0 
 eslint                               ^5.16.0  →         ^6.8.0 
 eslint-plugin-prettier                ^3.1.1  →         ^3.1.2 
 eslint-plugin-vue                     ^5.2.3  →         ^6.1.2 
 firebase-tools                        ^7.6.2  →        ^7.12.1 
 husky                                 ^3.0.9  →         ^4.2.1 
 jest-canvas-mock                      ^2.1.2  →         ^2.2.0 
 lint-staged                           ^9.4.2  →        ^10.0.2 
 node-sass                            ^4.13.0  →        ^4.13.1 
 prettier                             ^1.18.2  →        ^1.19.1 
 sass                                 ^1.23.3  →        ^1.25.0 
 sass-loader                           ^8.0.0  →         ^8.0.2 
 start-server-and-test                ^1.10.6  →        ^1.10.7 
 ts-jest                              ^24.1.0  →        ^25.0.0 
 typescript                            ^3.6.4  →         ^3.7.5 
 vue-cli-plugin-vuetify                ^1.1.1  →         ^2.0.3 
 vue-loader                           ^15.7.2  →        ^15.8.3 
 vue-template-compiler                ^2.6.10  →        ^2.6.11 
 vuetify-loader                        ^1.3.0  →         ^1.4.3 
 webpack                              ^4.41.2  →        ^4.41.5
```
